// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "tickets/entity"

	mock "github.com/stretchr/testify/mock"
)

// FileService is an autogenerated mock type for the FileService type
type FileService struct {
	mock.Mock
}

// Put provides a mock function with given fields: ctx, ticket
func (_m *FileService) Put(ctx context.Context, ticket entity.TicketBookingConfirmed) (string, error) {
	ret := _m.Called(ctx, ticket)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.TicketBookingConfirmed) (string, error)); ok {
		return rf(ctx, ticket)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.TicketBookingConfirmed) string); ok {
		r0 = rf(ctx, ticket)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.TicketBookingConfirmed) error); ok {
		r1 = rf(ctx, ticket)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFileService interface {
	mock.TestingT
	Cleanup(func())
}

// NewFileService creates a new instance of FileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFileService(t mockConstructorTestingTNewFileService) *FileService {
	mock := &FileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
